In [1]:
import numpy as np

In [2]:
board = [
    [8,7,0,5,0,0,0,0,0],
    [6,0,0,7,0,0,5,0,0],
    [3,0,0,0,4,0,0,0,0],
    [0,3,0,9,0,0,0,2,5],
    [4,0,0,0,3,0,0,0,9],
    [7,9,0,0,0,1,0,8,0],
    [0,0,0,0,2,0,0,0,7],
    [0,0,3,0,0,9,0,0,1],
    [0,0,0,0,0,5,0,9,8],
]

In [3]:
print(np.matrix(board))

[[8 7 0 5 0 0 0 0 0]
 [6 0 0 7 0 0 5 0 0]
 [3 0 0 0 4 0 0 0 0]
 [0 3 0 9 0 0 0 2 5]
 [4 0 0 0 3 0 0 0 9]
 [7 9 0 0 0 1 0 8 0]
 [0 0 0 0 2 0 0 0 7]
 [0 0 3 0 0 9 0 0 1]
 [0 0 0 0 0 5 0 9 8]]


In [4]:
# check possability
def possible(y,x,n): #y-axis,x-axis, place
    for i in range(0,9):
        if board[y][i] == n:
            return False
    for i in range(0,9):
        if board[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if board[y0+i][x0+j] == n:
                return False
    return True

you can run a possabilitiy test, for instance: Can you insert the number 3 at y=4,x=4 given the predetermined values of the board?

In [18]:
possible(4,4,9)

False

In [8]:
#implenting a solver using a backtracking attempt
def solve():
    global board
    for y in range(9):
        for x in range(9):
            if board[y][x]==0:
                for n in range(1,10):
                    if possible(y,x,n):
                        board[y][x] = n
                        solve()
                        board[y][x]=0
                return      
    print(np.matrix(board))

# in order to find alternative solution you can actually delete one of the predetermined values of the board matrix.   
    input("Do alternative solutions exists?")

In [9]:
solve()

[[8 7 4 5 6 3 9 1 2]
 [6 2 1 7 9 8 5 3 4]
 [3 5 9 1 4 2 8 7 6]
 [1 3 6 9 8 4 7 2 5]
 [4 8 5 2 3 7 1 6 9]
 [7 9 2 6 5 1 4 8 3]
 [9 1 8 4 2 6 3 5 7]
 [5 6 3 8 7 9 2 4 1]
 [2 4 7 3 1 5 6 9 8]]
Do alternative solutions exists?
